#  WARNING   #
# Not for production use, strictly for development

version: '3.6'

services:
  server:
    build: .
    networks:
      - internal
    volumes:
      - .:/app
      - cache:/go/pkg/mod
    ports:
      - 5000:5000
    env_file:
      - ./example.db.env
      - ./example.conf.env
    working_dir: /app
    container_name: fspexet-backend

  postgres:
    restart: always
    image: postgres:11
    networks:
      - internal
    env_file:
      - ./example.db.env
    volumes:
      - db:/var/lib/postgresql
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: fspexet-backend-postgres


networks:
  internal:
    driver: bridge
    name: fspexet-backend-internal
volumes:
  cache:
  db: